[project]
name = "bench"
version = "0.1.0"
description = "Performance benchmarking"
authors = [
    { name = "Emiliano Bonilla", email = "56323762+emilbon99@users.noreply.github.com" },
]
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "influxdb-client>=1.46.0",
    "synnax>=0.32.0",
    "docker>=7.1.0",
    "psycopg2-binary>=2.9.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
